label = "Portfolio 10"

[[funds]]
name = "ICICI Prudential Bluechip Fund"
url = "https://api.mfapi.in/mf/120586"
allocation = 0.10
asset_allocation = {equity = 92.69, debt = 0.35, real_estate = 0.00, commodities = 0.00, cash = 6.96}

[[funds]]
name = "DSP Global Allocation Fund"
url = "https://api.mfapi.in/mf/130493"
allocation = 0.15
asset_allocation = {equity = 97.36, debt = 1.14, real_estate = 0.66, commodities = 0.00, cash = 1.50}

[[funds]]
# ChatGPT recommended the IDBI Banking & PSU Debt Fund, but I couldn't find that.
# The only similar name I found was the IDBI Banking & Financial Services Fund.
# For some reason I put this in its place: Bhandan Banking & PSU Debt Fund.
name = "IDBI Banking and PSU Debt Fund"
url = "https://api.mfapi.in/mf/121279"
allocation = 0.15
asset_allocation = {equity = 0.00, debt = 97.78, real_estate = 0.00, commodities = 0.00, cash = 2.22}

[[funds]]
name = "HDFC Balanced Advantage Fund"
url = "https://api.mfapi.in/mf/118968"
allocation = 0.20
asset_allocation = {equity = 53.34, debt = 29.91, real_estate = 1.44, commodities = 0.00, cash = 15.31}

[[funds]]
name = "HDFC Hybrid Debt Fund"
url = "https://api.mfapi.in/mf/119118"
allocation = 0.15
asset_allocation = {equity = 21.86, debt = 73.35, real_estate = 0.66, commodities = 0.00, cash = 4.13}

[[funds]]
name = "ICICI Prudential Liquid Fund"
url = "https://api.mfapi.in/mf/120197"
allocation = 0.10
asset_allocation = {equity = 0.00, debt = 96.74, real_estate = 0.00, commodities = 0.00, cash = 3.26}

[[funds]]
name = "HDFC Gold ETF Fund of_Fund"
url = "https://api.mfapi.in/mf/119132"
allocation = 0.15
asset_allocation = {equity = 0.00, debt = 0.00, real_estate = 0.00, commodities = 98.29, cash = 1.71}
