# Portfolio 4
#
# This portfolio was meant to enhance returns as compared to Portfolio 3 while keeping
# drawdowns low. As of 1 Dec., 2024, results were:
#
# * Cumulative returns of about 300%.
# * Peak drawdowns for 2020, 2022, and 2024 were about 50%, 35%, and 15%, respectively.
#
# Here's the approach:
#
# * Rebelance asset allocations by shifting slightly more allocation toward
#   higher-performing assets (e.g., large-cap equities and balanced funds) while still
#   maintaining exposure to stable assets (e.g., bonds, gold).
# * Optomise gold allocation by adjusting its allocation slightly downward to free up
#   resources for higher-return asset classes without increasing volatility
#   significantly.
# * Incorporate another diversifier: introduce a higher-return dynamic or hybrid fund,
#   which can adapt to changing market conditions, potentially improving returns while
#   maintaining stability.

label = "Portfolio 4 (Like Port. 3 with Higher Returns)"

[[funds]]
name = "ICICI_Prudential_Bluechip_Fund"
url = "https://api.mfapi.in/mf/120586"
allocation = 0.25
asset_allocation = {equity = 92.69, debt = 0.35, real_estate = 0.00, commodities = 0.00, cash = 6.96}

[[funds]]
name = "Franklin_US_Opportunities_Fund"
url = "https://api.mfapi.in/mf/116633"
allocation = 0.10
asset_allocation = {equity = 98.79, debt = 0.00, real_estate = 0.00, commodities = 0.00, cash = 1.21}

[[funds]]
name = "HDFC_Balanced_Advantage_Fund"
url = "https://api.mfapi.in/mf/118968"
allocation = 0.25
asset_allocation = {equity = 53.34, debt = 29.91, real_estate = 1.44, commodities = 0.00, cash = 15.31}

[[funds]]
name = "ICICI_Prudential_Corporate_Bond_Fund"
url = "https://api.mfapi.in/mf/120692"
allocation = 0.20
asset_allocation = {equity = 0.00, debt = 97.10, real_estate = 0.00, commodities = 0.00, cash = 2.90}

[[funds]]
name = "HDFC_Hybrid_Debt_Fund"
url = "https://api.mfapi.in/mf/119118"
allocation = 0.15
asset_allocation = {equity = 21.86, debt = 73.35, real_estate = 0.66, commodities = 0.00, cash = 4.13}

[[funds]]
name = "SBI_Gold_Fund"
url = "https://api.mfapi.in/mf/102885"
allocation = 0.05
asset_allocation = {equity = 0.00, debt = 0.00, real_estate = 0.00, commodities = 98.37, cash = 1.63}
