label = "HDFC Mid-Cap Opportunities Fund"

benchmark_name = "Nifty Midcap 150 Index"

[[funds]]
name = "HDFC Mid-Cap Opportunities Fund"
url = "https://api.mfapi.in/mf/118989"  # See mfapi.in
allocation = 1.00
# Allocations from ValueResearchOnline.com
asset_allocation = {equity = 92.47, debt = 0.00, real_estate = 0.00, commodities = 0.00, cash = 7.53}
