# Portfolio 5
#
# This portfolio was to achieve a high annualised return, while keeping the
# drawdown in 2020 to not more than 60% and drawdown in 2022 of 40% or less.
#
# * Cumulative returns of about 290%.
# * Peak drawdowns for 2020, 2022, and 2024 were about 48%, 33%, and 14%, respectively.
#
# Here's the approach:
#
# * Use allocations to balanced and hybrid funds to mitigate drawdowns.
# * Be careful not to allocate too much to volatile assets like sectoral and
#   international funds.
# * Target growth and stability by balancing equity exposure between large-cap and
#   international funds, and by retaining a small allocation to high-growth sectoral
#   funds for cumulative return improvement.
# * ChatGPT said 'Adjust allocations iteratively, balancing drawdowns and cumulative
#   returns', but I don't understand that.

label = "Portfolio 5 (High Return, Capped Drawdowns in 2020/22/24)"

[[funds]]
name = "ICICI Prudential Bluechip Fund"
url = "https://api.mfapi.in/mf/120586"
allocation = 0.20
asset_allocation = {equity = 92.69, debt = 0.35, real_estate = 0.00, commodities = 0.00, cash = 6.96}

[[funds]]
name = "Franklin US Opportunities Fund"
url = "https://api.mfapi.in/mf/116633"
allocation = 0.10
asset_allocation = {equity = 98.79, debt = 0.00, real_estate = 0.00, commodities = 0.00, cash = 1.21}

[[funds]]
name = "HDFC Balanced Advantage Fund"
url = "https://api.mfapi.in/mf/118968"
allocation = 0.25
asset_allocation = {equity = 53.34, debt = 29.91, real_estate = 1.44, commodities = 0.00, cash = 15.31}

[[funds]]
name = "ICICI Prudential Corporate Bond Fund"
url = "https://api.mfapi.in/mf/120692"
allocation = 0.20
asset_allocation = {equity = 0.00, debt = 97.10, real_estate = 0.00, commodities = 0.00, cash = 2.90}

[[funds]]
name = "HDFC Hybrid Debt_Fund"
url = "https://api.mfapi.in/mf/119118"
allocation = 0.20
asset_allocation = {equity = 21.86, debt = 73.35, real_estate = 0.66, commodities = 0.00, cash = 4.13}

[[funds]]
name = "SBI Gold Fund"
url = "https://api.mfapi.in/mf/102885"
allocation = 0.05
asset_allocation = {equity = 0.00, debt = 0.00, real_estate = 0.00, commodities = 98.37, cash = 1.63}
