label = "Portfolio HDFC Mid-Cap Opportunities Fund"

[[funds]]
name = "HDFC Mid-Cap Opportunities Fund"
url = "https://api.mfapi.in/mf/118989"
allocation = 1.00
asset_allocation = {equity = 92.47, debt = 7.53, real_estate = 0.00, commodities = 0.00, cash = 0.00}
