# Portfolio 3
#
# This portfolio was created to mitigate the possibility of severe drawdowns, such
# as those experienced in 2020 and 2022. As of 1 Dec., 2024, results were:
#
# * Cumulative returns of about 310%.
# * The peak drawdowns for 2020, 2022, and 2024 were about 50%, 40%, and 14%, respectively.
#
# Here's the approach:
#
# * Use debt funds, hybrid funds, and gold as stable assets, less volatile than
#   pure equities.
# * Use international funds that invest in different regions or sectors, reducing
#   exposure to specific market risks.
# * Reduce equity concentration in high-risk equity funds, especially those focused
#   on mid-cap or growth stocks.
# * Include dynamic asset allocation funds--funds that adjust their equity and
#   debt mix based on market conditions, providing a natural hedge during downturns.
# * Use assets with low or negative correlation to equity markets, such as funds
#   focusing on alternative investments or commodities. 

label = "Portfolio 3 (Mitigate Severe Drawdowns)"

[[funds]]
name = "ICICI Prudential Bluechip Fund"
url = "https://api.mfapi.in/mf/120586"
allocation = 0.20
asset_allocation = {equity = 92.69, debt = 0.35, real_estate = 0.00, commodities = 0.00, cash = 6.96}

[[funds]]
name = "Franklin US Opportunities Fund"
url = "https://api.mfapi.in/mf/116633"
allocation = 0.15
asset_allocation = {equity = 98.79, debt = 0.00, real_estate = 0.00, commodities = 0.00, cash = 1.21}

[[funds]]
name = "HDFC Balanced Advantage Fund"
url = "https://api.mfapi.in/mf/118968"
allocation = 0.20
asset_allocation = {equity = 53.34, debt = 29.91, real_estate = 1.44, commodities = 0.00, cash = 15.31}

[[funds]]
name = "ICICI Prudential Corporate Bond Fund"
url = "https://api.mfapi.in/mf/120692"
allocation = 0.20
asset_allocation = {equity = 0.00, debt = 97.10, real_estate = 0.00, commodities = 0.00, cash = 2.90}

[[funds]]
name = "HDFC Hybrid Debt Fund"
url = "https://api.mfapi.in/mf/119118"
allocation = 0.15
asset_allocation = {equity = 21.86, debt = 73.35, real_estate = 0.66, commodities = 0.00, cash = 4.13}

[[funds]]
name = "SBI Gold Fund"
url = "https://api.mfapi.in/mf/102885"
allocation = 0.10
asset_allocation = {equity = 0.00, debt = 0.00, real_estate = 0.00, commodities = 98.37, cash = 1.63}
