label = "Portfolio ICICI NIFTY: NIFTY50"

[[funds]]
name = "ICICI_Nifty_50_Index_Fund"
url = "https://api.mfapi.in/mf/120620"
allocation = 1.00
asset_allocation = {equity = 99.89, debt = 0.00, real_estate = 0.00, commodities = 0.00, cash = 0.11}
