label = "Portfolio 8 with 40% in PPF"

[[funds]]
name = "ICICI Prudential Bluechip Fund"
url = "https://api.mfapi.in/mf/120586"
allocation = 0.10526315789473684
asset_allocation = {equity = 92.69, debt = 0.35, real_estate = 0.00, commodities = 0.00, cash = 6.96}

[[funds]]
name = "HDFC Balanced Advantage Fund"
url = "https://api.mfapi.in/mf/118968"
allocation = 0.1631578947368421
asset_allocation = {equity = 53.34, debt = 29.91, real_estate = 1.44, commodities = 0.00, cash = 15.31}

[[funds]]
name = "ICICI Prudential Corporate Bond Fund"
url = "https://api.mfapi.in/mf/120692"
allocation = 0.16842105263157887
asset_allocation = {equity = 0.00, debt = 97.10, real_estate = 0.00, commodities = 0.00, cash = 2.90}

[[funds]]
name = "HDFC Hybrid Debt Fund"
url = "https://api.mfapi.in/mf/119118"
allocation = 0.11052631578947367
asset_allocation = {equity = 21.86, debt = 73.35, real_estate = 0.66, commodities = 0.00, cash = 4.13}

[[funds]]
name = "SBI Gold Fund"
url = "https://api.mfapi.in/mf/102885"
allocation = 0.05263157894736842
asset_allocation = {equity = 0.00, debt = 0.00, real_estate = 0.00, commodities = 98.37, cash = 1.63}

[ppf]
name = "Public Provident Fund"
allocation = 0.40
